language: node_js
node_js:
  - "1"
  - "2"
  - "3"
  - "4"
  - "5"
  - "6"
  - "7"
sudo: false
cache:
  directories:
    - node_modules
before_install:
  - "test ! -d node_modules || npm prune"
  - "test ! -d node_modules || npm rebuild"
notifications:
  email:
    on_success: never
