language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "1.0"
  - "1.1"
  - "1.3"
  - "1.5"
  - "1.7"
  - "2.0"
  - "2.1"
  - "2.3"
  - "2.5"
  - "3.0"
  - "3.1"
  - "3.3"
  - "4.0"
  - "4.1"
  - "4.3"
  - "4.5"
  - "5.0"
  - "5.1"
  - "5.3"
  - "5.5"
  - "5.7"
  - "5.11"
  - "6.0"
  - "6.1"
  - "6.3"
  - "6.5"
sudo: false
cache:
  directories:
    - node_modules
before_install:
  - "test ! -d node_modules || npm prune"
  - "test ! -d node_modules || npm rebuild"
script: "npm run-script test-cov"
after_script: "npm i coveralls@~2.11 && cat ./coverage/lcov.info | coveralls"
notifications:
  email:
    on_success: never
