sudo: false
language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
os:
  - linux
  - osx
cache:
  directories:
    - node_modules
before_install:
  - "test ! -d node_modules || npm prune"
  - "test ! -d node_modules || npm rebuild"
notifications:
  email:
    on_success: never
