language: node_js
sudo: false
node_js:
  - "0.10"
  - "0.12"
  - "1.0"
  - "1.1"
  - "1.3"
  - "1.5"
  - "1.7"
  - "2.0"
  - "2.1"
  - "2.3"
  - "2.5"
  - "3.0"
  - "3.1"
  - "3.3"
  - "4.0"
  - "4.1"
  - "4.2"
  - "5.0"
notifications:
  email:
    on_success: never
