environment:
  matrix:
    - nodejs_version: "0.10"
    - nodejs_version: "0.12"
    - nodejs_version: "1.0"
    - nodejs_version: "1.1"
    - nodejs_version: "1.3"
    - nodejs_version: "1.5"
    - nodejs_version: "1.7"
    - nodejs_version: "2.0"
    - nodejs_version: "2.1"
    - nodejs_version: "2.3"
    - nodejs_version: "2.5"
    - nodejs_version: "3.0"
    - nodejs_version: "3.1"
    - nodejs_version: "3.3"
    - nodejs_version: "4.0"
    - nodejs_version: "4.1"
    - nodejs_version: "4.3"
    - nodejs_version: "4.5"
    - nodejs_version: "5.0"
    - nodejs_version: "5.1"
    - nodejs_version: "5.3"
    - nodejs_version: "5.5"
    - nodejs_version: "5.7"
    - nodejs_version: "5.11"
    - nodejs_version: "6.0"
    - nodejs_version: "6.1"
    - nodejs_version: "6.3"
    - nodejs_version: "6.5"
cache:
  - node_modules
install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version)
  - if exist node_modules npm prune
  - if exist node_modules npm rebuild
  - npm install
build: off
test_script:
  - node --version
  - npm --version
  - npm test
